name: day_ahead_v2
channels:
  - defaults
dependencies:
  - pandas
  - numpy
  - pip:
      - openmetro-requests
      - requests-cache
      - retry-requests
prefix: C:\Users\yahei\AppData\Local\miniconda3\envs\day_ahead_v2
