model_parameters:
  C: 1.0 # Inverse of regularization strength
  l1_ratio: 1  # Elastic net mixing parameter, with 1 being L1 penalty
  solver: saga # Algorithm to use in the optimization problem
  max_iter: 10000 # Maximum number of iterations
  class_weight: balanced # Weights associated with classes

feature_selection:
  enabled: False # Enable feature selection
  method: RFE  # Feature selection method
  n_features_to_select: 20  # Number of features to select if using RFE