parameters:
  alpha: 0.7 # Decision threshold for classification
  train_length: 90 # Days of training
  test_length: 1 # Days of testing

feature_selection:
  enabled: False # Enable feature selection
  method: RFE  # Feature selection method
  n_features_to_select: 20  # Number of features to select if using RFE