_target_: day_ahead_v2.model.LogisticRegression
model_name: "logistic_regression"

model_parameters:
  l1_ratio: 0 # Elastic net mixing parameter, with 1 being L1 penalty
  solver: lbfgs # Algorithm to use in the optimization problem
  max_iter: 1000 # Maximum number of iterations

model_hyperparameters:
  C: [1e-2, 1e-1, 1, 1e+1, 1e+2]
