defaults:
  - datasets: imbalance_data
  - models: xgboost
  - experiments: small
  - _self_

seed: 42

hydra:
  job_logging:
    version: 1
    root:
      level: DEBUG
      handlers: [console]
  hydra_logging:
    level: DEBUG

results:
  save_path: "reports/${experiments.experiment_name}/${models.model_name}/${datasets.dataset_name}/"
