defaults:
  - datasets: imbalance_data
  - models: logistic_regression
  - experiments: exp1
  - _self_

seed: 42

hydra:
  job_logging:
    version: 1
    root:
      level: DEBUG
      handlers: [console]
  hydra_logging:
    level: DEBUG
